### ISSUE TITLE
Berkshire list index out of range

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/luxalert#1]
Got this on 2/28 and 3/2, never since.  Looks like we need to handle the case where the unit_dict's price_ids list is empty; not sure what that means though.  Any ideas?

```
2018-03-02 00:18:25,685:nest.ingest.ApartmentProcessor:ERROR:rolling back
Traceback (most recent call last):
  File "/home/sormtger/luxalert/nest/ingest/ApartmentProcessor.py", line 58, in store_apartment_data
    for scraped_apt, scraped_apt_snap in apt_data_gen:
  File "/home/sormtger/luxalert/luxweb/api_spiders/BerkshireSpider.py", line 69, in get_api_data
    if unit_dict["price_ids"][0] == price["id"]:
IndexError: list index out of range
2018-03-02 00:18:25,705:scrape_for_data.py:ERROR:rolling back, then continuing
Traceback (most recent call last):
  File "scrape_for_data.py", line 43, in <module>
    api_spider.get_api_data(),
  File "/home/sormtger/luxalert/nest/ingest/ApartmentProcessor.py", line 58, in store_apartment_data
    for scraped_apt, scraped_apt_snap in apt_data_gen:
  File "/home/sormtger/luxalert/luxweb/api_spiders/BerkshireSpider.py", line 69, in get_api_data
    if unit_dict["price_ids"][0] == price["id"]:
IndexError: list index out of range
```

**Comment by raph23** [comment]
Not sure what that means either... I feel we should store the raw API
responses just for debugging purposes.

I have this project running, with all the code for my legacy project, I
added the API data dumps there: https://github.com/raph23/luxbackup

Also shows we need that error email.

**Comment by LittleRichard** [comment]
Got that list-index-out-of-range error again, which is what failed the 8:30pm run today.

When the 9:30pm run went through okay, I also see a few of these.  Not sure how/why, but here's what it's barfing on.  Can you take a look at this with your API parsing code?
```
2018-03-14 21:10:18,832:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473340], u'display_name': u'415', u'name': u'415', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-06', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755822', u'id': 150476101, u'price_ids': []}
2018-03-14 21:10:18,833:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473341], u'display_name': u'119', u'name': u'119', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2017-10-29', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755761', u'id': 150476105, u'price_ids': []}
2018-03-14 21:10:18,833:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473342], u'display_name': u'214', u'name': u'214', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-10', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755777', u'id': 150476109, u'price_ids': []}
2018-03-14 21:10:18,834:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473345], u'display_name': u'308', u'name': u'308', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2017-09-23', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755792', u'id': 150476112, u'price_ids': []}
2018-03-14 21:10:18,835:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473346], u'display_name': u'506', u'name': u'506', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-06', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755834', u'id': 150476119, u'price_ids': []}
2018-03-14 21:10:18,835:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473347], u'display_name': u'406', u'name': u'406', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-15', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755812', u'id': 150476123, u'price_ids': []}
2018-03-14 21:10:18,836:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473348], u'display_name': u'219', u'name': u'219', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-27', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755782', u'id': 150476127, u'price_ids': []}
2018-03-14 21:10:18,837:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473349], u'display_name': u'317', u'name': u'317', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755802', u'id': 150476129, u'price_ids': []}
2018-03-14 21:10:18,838:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473343], u'display_name': u'209', u'name': u'209', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-22', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755771', u'id': 150476133, u'price_ids': []}
2018-03-14 21:10:18,839:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113473339, 113473344], u'display_name': u'509', u'name': u'509', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-18', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7755837', u'id': 150476136, u'price_ids': []}
2018-03-14 21:10:18,839:luxweb.api_spiders.BerkshireSpider:DEBUG:Sleeping 1 seconds between requests
2018-03-14 21:10:20,692:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474272], u'display_name': u'02-108', u'name': u'02-108', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754555', u'id': 150477232, u'price_ids': []}
2018-03-14 21:10:20,693:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474273], u'display_name': u'02-802', u'name': u'02-802', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-26', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754641', u'id': 150477236, u'price_ids': []}
2018-03-14 21:10:20,694:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474274], u'display_name': u'06-115', u'name': u'06-115', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754381', u'id': 150477241, u'price_ids': []}
2018-03-14 21:10:20,695:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474276], u'display_name': u'02-508', u'name': u'02-508', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-11', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754608', u'id': 150477246, u'price_ids': []}
2018-03-14 21:10:20,695:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474277], u'display_name': u'06-410', u'name': u'06-410', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-23', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754672', u'id': 150477249, u'price_ids': []}
2018-03-14 21:10:20,696:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474281], u'display_name': u'02-710', u'name': u'02-710', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754637', u'id': 150477257, u'price_ids': []}
2018-03-14 21:10:20,697:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474283], u'display_name': u'06-211', u'name': u'06-211', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754503', u'id': 150477263, u'price_ids': []}
2018-03-14 21:10:20,697:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474285], u'display_name': u'10-805', u'name': u'10-805', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-23', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754541', u'id': 150477274, u'price_ids': []}
2018-03-14 21:10:20,698:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474287], u'display_name': u'08-506', u'name': u'08-506', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754413', u'id': 150477281, u'price_ids': []}
2018-03-14 21:10:20,699:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474279], u'display_name': u'06-601', u'name': u'06-601', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-26', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754698', u'id': 150477289, u'price_ids': []}
2018-03-14 21:10:20,700:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474290], u'display_name': u'02-803', u'name': u'02-803', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-26', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754642', u'id': 150477298, u'price_ids': []}
2018-03-14 21:10:20,700:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474291], u'display_name': u'10-301', u'name': u'10-301', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-05', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754482', u'id': 150477304, u'price_ids': []}
2018-03-14 21:10:20,701:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474294], u'display_name': u'10-601', u'name': u'10-601', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-03', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754515', u'id': 150477309, u'price_ids': []}
2018-03-14 21:10:20,702:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474295], u'display_name': u'02-406', u'name': u'02-406', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-25', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754593', u'id': 150477315, u'price_ids': []}
2018-03-14 21:10:20,702:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474298], u'display_name': u'06-305', u'name': u'06-305', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-27', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754614', u'id': 150477324, u'price_ids': []}
2018-03-14 21:10:20,703:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474303], u'display_name': u'06-505', u'name': u'06-505', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-06', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754684', u'id': 150477329, u'price_ids': []}
2018-03-14 21:10:20,704:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474304], u'display_name': u'10-406', u'name': u'10-406', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-20', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754498', u'id': 150477332, u'price_ids': []}
2018-03-14 21:10:20,704:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474306], u'display_name': u'08-802', u'name': u'08-802', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754450', u'id': 150477335, u'price_ids': []}
2018-03-14 21:10:20,705:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474308], u'display_name': u'06-614', u'name': u'06-614', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-21', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754712', u'id': 150477339, u'price_ids': []}
2018-03-14 21:10:20,706:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474310], u'display_name': u'02-409', u'name': u'02-409', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-15', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754596', u'id': 150477342, u'price_ids': []}
2018-03-14 21:10:20,706:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474312], u'display_name': u'06-808', u'name': u'06-808', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-10', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754347', u'id': 150477350, u'price_ids': []}
2018-03-14 21:10:20,707:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474315], u'display_name': u'02-609', u'name': u'02-609', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754622', u'id': 150477355, u'price_ids': []}
2018-03-14 21:10:20,708:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474318], u'display_name': u'02-709', u'name': u'02-709', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-29', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754635', u'id': 150477361, u'price_ids': []}
2018-03-14 21:10:20,709:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474322], u'display_name': u'10-104', u'name': u'10-104', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754464', u'id': 150477366, u'price_ids': []}
2018-03-14 21:10:20,709:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474325], u'display_name': u'10-804', u'name': u'10-804', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-16', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754540', u'id': 150477372, u'price_ids': []}
2018-03-14 21:10:20,710:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474326], u'display_name': u'02-611', u'name': u'02-611', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-29', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754624', u'id': 150477376, u'price_ids': []}
2018-03-14 21:10:20,711:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474327], u'display_name': u'08-509', u'name': u'08-509', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-31', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754417', u'id': 150477381, u'price_ids': []}
2018-03-14 21:10:20,712:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474328], u'display_name': u'02-505', u'name': u'02-505', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-15', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754605', u'id': 150477384, u'price_ids': []}
2018-03-14 21:10:20,712:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474329], u'display_name': u'06-203', u'name': u'06-203', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-17', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754414', u'id': 150477388, u'price_ids': []}
2018-03-14 21:10:20,713:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474332], u'display_name': u'08-710', u'name': u'08-710', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-23', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754445', u'id': 150477390, u'price_ids': []}
2018-03-14 21:10:20,714:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474333], u'display_name': u'02-404', u'name': u'02-404', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-28', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754590', u'id': 150477396, u'price_ids': []}
2018-03-14 21:10:20,714:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474335], u'display_name': u'02-205', u'name': u'02-205', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-01', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754565', u'id': 150477400, u'price_ids': []}
2018-03-14 21:10:20,715:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474336], u'display_name': u'10-302', u'name': u'10-302', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754483', u'id': 150477406, u'price_ids': []}
2018-03-14 21:10:20,716:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474337], u'display_name': u'02-604', u'name': u'02-604', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-24', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754617', u'id': 150477410, u'price_ids': []}
2018-03-14 21:10:20,716:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474271, 113474338], u'display_name': u'10-303', u'name': u'10-303', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-15', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7754484', u'id': 150477416, u'price_ids': []}
2018-03-14 21:10:20,717:luxweb.api_spiders.BerkshireSpider:DEBUG:Sleeping 4 seconds between requests
2018-03-14 21:10:25,532:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474125], u'display_name': u'A-A218', u'name': u'A-A218', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-28', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756257', u'id': 150477081, u'price_ids': []}
2018-03-14 21:10:25,533:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474126], u'display_name': u'A-A224', u'name': u'A-A224', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-02', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756263', u'id': 150477089, u'price_ids': []}
2018-03-14 21:10:25,535:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474128], u'display_name': u'A-A104', u'name': u'A-A104', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-28', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756247', u'id': 150477095, u'price_ids': []}
2018-03-14 21:10:25,536:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474129], u'display_name': u'B-B103', u'name': u'B-B103', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-26', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756189', u'id': 150477103, u'price_ids': []}
2018-03-14 21:10:25,538:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474115], u'display_name': u'B-B305', u'name': u'B-B305', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-06-04', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756215', u'id': 150477109, u'price_ids': []}
2018-03-14 21:10:25,539:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474117], u'display_name': u'B-B102', u'name': u'B-B102', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-03-11', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756187', u'id': 150477115, u'price_ids': []}
2018-03-14 21:10:25,540:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474112], u'display_name': u'A-A216', u'name': u'A-A216', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-01-24', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756256', u'id': 150477122, u'price_ids': []}
2018-03-14 21:10:25,542:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474114], u'display_name': u'A-A221', u'name': u'A-A221', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-05-29', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756260', u'id': 150477128, u'price_ids': []}
2018-03-14 21:10:25,543:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474118], u'display_name': u'A-A203', u'name': u'A-A203', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-19', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756244', u'id': 150477135, u'price_ids': []}
2018-03-14 21:10:25,545:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474120], u'display_name': u'A-A401', u'name': u'A-A401', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-02-28', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756148', u'id': 150477139, u'price_ids': []}
2018-03-14 21:10:25,546:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474122], u'display_name': u'A-A322', u'name': u'A-A322', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2018-04-13', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756297', u'id': 150477147, u'price_ids': []}
2018-03-14 21:10:25,547:luxweb.api_spiders.BerkshireSpider:DEBUG:Could not identify critical information for unit {u'building': None, u'call_to_action_ids': [113474111, 113474123], u'display_name': u'A-A309', u'name': u'A-A309', u'sqft_display': None, u'special_ids': [], u'availability_date': u'2017-11-09', u'offer_term_ids': [], u'amenity_ids': [], u'external_id': u'7756289', u'id': 150477154, u'price_ids': []}
```

**Comment by LittleRichard** [comment]
ruh roh, looks like berkshire has stopped posting prices completely...
https://www.berkshirecommunities.com/apartments/ma/boston/the-benjamin/floor-plans#/floorplans/79786478/apartments

still going to push a fix in branch: `issue1-berkshire_fixes`

**Comment by LittleRichard** [comment]
merged to master
