### ISSUE TITLE
related spider - strathmore page no longer exists

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/luxalert#13]
looks like this page is dead:
http://www.relatedrentals.com/apartment-rentals/new-york-city/upper-east-side/the-strathmore/available-apartments

```
2018-04-14 03:27:05,229:scrapy.core.engine:DEBUG:Crawled (200) <GET http://www.relatedrentals.com/apartment-rentals/new-york-city/upper-east-side/the-strathmore/available-apartments> (referer: None)
2018-04-14 03:27:05,333:luxweb.luxweb.ScrapeErrorHandler:ERROR:returning garbage data tuple
Traceback (most recent call last):
  File "/home/luxalert/luxalert/luxweb/luxweb/ScrapeErrorHandler.py", line 22, in new_function
    for x in original_function(*args, **kwargs):
  File "/home/luxalert/luxalert/luxweb/luxweb/spiders/RelatedSpider.py", line 124, in parse
    building = buildings_by_name[building_str]
KeyError: 'Page Not Found'
```

it may recover eventually, but we should handle this by:
- extract the `building_str`
- look for the string `u'Page Not Found'`, log and `continue` if its the building name

**Comment by LittleRichard** [comment]
https://github.com/LittleRichard/luxalert/commit/9a34b0e1fb24cbef31b3fd73ea73e562eb62771b

seems to have fixed it, deployed to droplet but won't be able to do the raspberry pi until the morning
