### ISSUE TITLE
ParklaneSpider price error

### ISSUE THREAD

**Issue by LittleRichard** [LittleRichard/luxalert#9]
```
2018-04-02 00:27:43,036:luxweb.luxweb.ScrapeErrorHandler:ERROR:returning garbage data tuple
Traceback (most recent call last):
  File "/home/luxalert/luxalert/luxweb/luxweb/ScrapeErrorHandler.py", line 22, in new_function
    for x in original_function(*args, **kwargs):
  File "/home/luxalert/luxalert/luxweb/luxweb/spiders/ParklaneSpider.py", line 94, in parse
    price = float(price)
ValueError: could not convert string to float: Call
```

@raph23 , you around to take a stab at this one?

**Comment by raph23** [comment]
I’m at an Easter dinner, but could potentially look later. What should I do? Set price as 0 when it’s “call”?

**Comment by LittleRichard** [comment]
no problem, i'll zap it now

**Comment by LittleRichard** [comment]
merged to master and deployed to DO/RPi:
https://github.com/LittleRichard/luxalert/commit/14039af6133abdc98b25f857cc15890302e70b0d
